insert into language (jp,en,cn) values ('固有技','special','固有技');
insert into language (jp,en,cn) values ('投げ技ほか','catch','投技');
insert into language (jp,en,cn) values ('基本技','basic','基本技');
insert into language (jp,en,cn) values ('リスク','beat','对策解说');
insert into language (jp,en,cn) values ('主要技解説','mainSkill','主要技能解说');
insert into language (jp,en,cn) values ('コンボ','combo','连技');
insert into language (jp,en,cn) values ('確定反撃','counter','确反');

insert into language (en,jp) values('unknown','アンノウン');
insert into language (en,jp) values('violet','ヴァイオレット');
insert into language (en,jp) values('doctorb','ボスコノビッチ');
insert into language (en,jp) values('slimbob','スリムボブ');
insert into language (en,jp) values('sebastian','セバスチャン');
insert into language (en,jp) values('miharu','美晴');
insert into language (en,jp) values('alex','アレックス');
insert into language (en,jp) values('prototype','P.ジャック');
insert into language (en,jp) values('tiger','タイガー');
insert into language (en,jp) values('forest','フォレスト');
insert into language (en,jp) values('michelle','ミシェール');
insert into language (en,jp) values('angel','エンジェル');
insert into language (en,jp) values('ancient','エンシェントオーガ');
insert into language (en,jp) values('kunimitsu','州光');
insert into language (en,jp) values('combot','コンボット');
insert into language (en,jp) values('jinpachi','仁八');
insert into language (en,jp) values('ogre','オーガ');
insert into language (en,jp) values('jun','準');
insert into language (en,jp) values('jaycee','ジェイシー');
insert into language (en,jp) values('heihachi','平八');
insert into language (en,jp) values('jin','仁');
insert into language (en,jp) values('kazuya','一八');
insert into language (en,jp) values('asuka','飛鳥');
insert into language (en,jp) values('lili','リリ');
insert into language (en,jp) values('hwoarang','ファラン');
insert into language (en,jp) values('ling','シャオユウ');
insert into language (en,jp) values('christie','クリスティ/エディ');
insert into language (en,jp) values('feng','フェン');
insert into language (en,jp) values('lei','レイ');
insert into language (en,jp) values('lee','リー');
insert into language (en,jp) values('paul','ポール');
insert into language (en,jp) values('marshall','(マーシャル)ロウ');
insert into language (en,jp) values('steve','スティーブ');
insert into language (en,jp) values('craig','マードック');
insert into language (en,jp) values('king','キング');
insert into language (en,jp) values('armorking','アーマーキング');
insert into language (en,jp) values('ganryu','巌竜');
insert into language (en,jp) values('nina','ニーナ');
insert into language (en,jp) values('anna','アンナ');
insert into language (en,jp) values('yoshimitsu','吉光');
insert into language (en,jp) values('bryan','ブライアン');
insert into language (en,jp) values('jack6','ジャック6');
insert into language (en,jp) values('panda','クマ/パンダ');
insert into language (en,jp) values('roger','ロジャーJr.');
insert into language (en,jp) values('wang','ワン');
insert into language (en,jp) values('bruce','ブルース');
insert into language (en,jp) values('baek','ペク');
insert into language (en,jp) values('raven','レイヴン');
insert into language (en,jp) values('dragunov','ドラグノフ');
insert into language (en,jp) values('deviljin','デビル仁');
insert into language (en,jp) values('leo','レオ');
insert into language (en,jp) values('zafina','ザフィーナ');
insert into language (en,jp) values('miguel','ミゲル');
insert into language (en,jp) values('bob','ボブ');
insert into language (en,jp) values('lars','ラース');
insert into language (en,jp) values('alisa','アリサ');
insert into language (en,jp) values('mokujin','木人');

insert into language (jp,en) values ('ロウ','law');
insert into language (jp,en) values ('ジュリア','julia');